### ISSUE TITLE
error: filename in tree entry contains backslash: '.\BuildReports'

### ISSUE THREAD

**Issue by Rasec77** [owlvey/owlvey_falcon#15]
Cloning into 'owlvey_falcon'...
remote: Enumerating objects: 394, done.
remote: Counting objects: 100% (394/394), done.
remote: Compressing objects: 100% (261/261), done.
error: filename in tree entry contains backslash: '.\BuildReports'
fatal: Not all child objects of 3b859c82204dd7be756933c6dea3148c8fc34beb are reachable
fatal: index-pack failed

<img width="491" alt="Issue_falcon" src="https://user-images.githubusercontent.com/3707647/71755100-2ec64680-2e57-11ea-8308-d75a93290d06.PNG">

**Comment by gcvalderrama** [comment]
Hi, Seems like problem with the newest version 
https://stackoverflow.com/questions/59345571/pycharm-behaving-strange-with-git-filename-in-tree-entry-contains-backslash

Please use the workaround mentioned there.

Best Regards
